# Put your experiment limits in jobpairs.csv, not in this Makefile.
REPO_ROOT := ../..
DEG_PAR := 1
SLURMY_HOST ?= datalab
SLURMY_PARTITION ?= CPU-amd
BUILD_RECIPES := ../../building-dependencies/runsolver/build.sh
include $(REPO_ROOT)/templates/workflow.mk
