#!/usr/bin/env python
"""Build portable job artifacts on a Slurm compute node and download them."""

from __future__ import annotations

import argparse
import os
from pathlib import Path, PurePosixPath
import re
import shlex
import shutil
import subprocess
import sys
import tarfile
import tempfile
import time
from typing import Sequence


VERSION = "0.1.0"
DEFAULT_HOST = os.environ.get("SLURMY_HOST", "datalab")
NAME_RE = re.compile(r"^[A-Za-z0-9._-]+$")
MEMORY_RE = re.compile(r"^([0-9]+)(MB|MiB|GB|GiB|TB|TiB|M|G|T)?$", re.IGNORECASE)
FINAL_STATES = {
    "BOOT_FAIL",
    "CANCELLED",
    "COMPLETED",
    "DEADLINE",
    "FAILED",
    "NODE_FAIL",
    "OUT_OF_MEMORY",
    "PREEMPTED",
    "REVOKED",
    "TIMEOUT",
}


class BuildError(RuntimeError):
    """A remote build could not be prepared or completed."""


def run(
    command: Sequence[str], *, input_text: str | None = None, capture: bool = False
) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            command,
            input=input_text,
            text=True,
            check=True,
            capture_output=capture,
        )
    except FileNotFoundError as exc:
        raise BuildError(f"required command is not installed: {command[0]}") from exc
    except subprocess.CalledProcessError as exc:
        detail = (exc.stderr or exc.stdout or "").strip()
        suffix = f"\n{detail}" if detail else ""
        raise BuildError(f"command failed: {shlex.join(command)}{suffix}") from exc


def remote_user(host: str) -> str:
    result = run(["ssh", "-T", "-G", "--", host], capture=True)
    for line in result.stdout.splitlines():
        key, _, value = line.partition(" ")
        if key.lower() == "user" and NAME_RE.fullmatch(value):
            return value
    raise BuildError(f"could not determine a safe SSH username for {host!r}")


def checked_artifact(value: str) -> str:
    path = PurePosixPath(value)
    if path.is_absolute() or not path.parts or any(part in {"", ".", ".."} for part in path.parts):
        raise argparse.ArgumentTypeError("artifact paths must be relative and may not contain . or ..")
    return path.as_posix()


def checked_sbatch_option(value: str) -> str:
    if not value.startswith("--") or "\n" in value or "\r" in value:
        raise argparse.ArgumentTypeError("use a single-line --OPTION=VALUE")
    if value.startswith("--job-name") or value.startswith("--output") or value.startswith("--error"):
        raise argparse.ArgumentTypeError("Slurmy manages job-name, output, and error")
    return value


def checked_time(value: str) -> str:
    if not re.fullmatch(r"[0-9:-]+", value):
        raise argparse.ArgumentTypeError("time may contain only digits, colons, and hyphens")
    return value


def slurm_memory(value: str) -> str:
    """Convert explicit decimal/binary units to the MiB syntax Slurm accepts."""

    match = MEMORY_RE.fullmatch(value.strip())
    if not match or int(match.group(1)) <= 0:
        raise argparse.ArgumentTypeError(
            "memory must be a positive integer followed by M, G, T, MB, MiB, GB, GiB, TB, or TiB"
        )
    number = int(match.group(1))
    unit = (match.group(2) or "M").lower()
    bytes_per_unit = {
        "m": 1024**2,
        "mib": 1024**2,
        "mb": 1000**2,
        "g": 1024**3,
        "gib": 1024**3,
        "gb": 1000**3,
        "t": 1024**4,
        "tib": 1024**4,
        "tb": 1000**4,
    }[unit]
    mebibytes = (number * bytes_per_unit + 1024**2 - 1) // 1024**2
    return f"{mebibytes}M"


def make_context_archive(source: Path, destination: Path) -> None:
    if not source.is_dir():
        raise BuildError(f"build context is not a directory: {source}")
    with tarfile.open(destination, "w:gz") as archive:
        for child in sorted(source.iterdir(), key=lambda path: path.name):
            archive.add(child, arcname=child.name)


def build_job_script(args: argparse.Namespace, *, has_context: bool) -> str:
    directives = [
        f"#SBATCH --job-name=slurmy-build-{args.name}",
        "#SBATCH --output=build.log",
        "#SBATCH --error=build.log",
        f"#SBATCH --cpus-per-task={args.cpus_per_task}",
        f"#SBATCH --mem={args.memory}",
        f"#SBATCH --time={args.time}",
        *(f"#SBATCH {option}" for option in args.sbatch_option),
    ]
    context_setup = (
        'tar -xzf "$SLURMY_BUILD_ROOT/context.tar.gz" -C "$SLURMY_BUILD_WORK"'
        if has_context
        else ": # No local build context was supplied."
    )
    artifact_checks = "\n".join(
        f'[[ -e "$SLURMY_BUILD_OUTPUT"/{shlex.quote(artifact)} ]] || '
        f'{{ printf "%s\\n" {shlex.quote(f"Missing required artifact: {artifact}")} >&2; exit 1; }}'
        for artifact in args.artifact
    )
    return f"""#!/usr/bin/env bash
{chr(10).join(directives)}

# Generated by slurmy-build.py. This runs on one Slurm compute node.
set -euo pipefail

SLURMY_BUILD_ROOT=${{SLURM_SUBMIT_DIR:?Slurm did not set SLURM_SUBMIT_DIR}}
export SLURMY_BUILD_ROOT
export SLURMY_BUILD_WORK="$SLURMY_BUILD_ROOT/work"
export SLURMY_BUILD_OUTPUT="$SLURMY_BUILD_ROOT/output"

rm -rf -- "$SLURMY_BUILD_WORK" "$SLURMY_BUILD_OUTPUT"
mkdir -p -- "$SLURMY_BUILD_WORK" "$SLURMY_BUILD_OUTPUT"
{context_setup}

cd -- "$SLURMY_BUILD_WORK"
bash "$SLURMY_BUILD_ROOT/recipe.sh"

{artifact_checks}
echo "Slurmy build completed successfully."
"""


REMOTE_PREPARE = r"""
set -euo pipefail
build_id=$1
root="$HOME/Slurmy-builds/$build_id"
[[ ! -e "$root" ]] || { echo "Build directory already exists: $root" >&2; exit 1; }
mkdir -p -- "$root/incoming"
"""


REMOTE_SUBMIT = r"""
set -euo pipefail
build_id=$1
root="$HOME/Slurmy-builds/$build_id"
mv -- "$root"/incoming/* "$root"/
rmdir -- "$root/incoming"
cd -- "$root"
sbatch --parsable job.sh
"""


REMOTE_STATE = r"""
set -euo pipefail
job_id=$1
state=$(squeue --noheader --jobs "$job_id" --format='%T' | head -n 1)
if [[ -n "$state" ]]; then
    printf '%s\n' "$state"
    exit 0
fi
sacct -n -X -j "$job_id" --format=JobIDRaw,State --parsable2 2>/dev/null |
    awk -F'|' -v id="$job_id" '$1 == id { print $2; exit }'
"""


REMOTE_LOG = r"""
set -euo pipefail
build_id=$1
log="$HOME/Slurmy-builds/$build_id/build.log"
if [[ -f "$log" ]]; then cat -- "$log"; fi
"""


def normalize_state(value: str) -> str:
    return value.strip().upper().split()[0].rstrip("+") if value.strip() else ""


def execute_build(args: argparse.Namespace) -> None:
    recipe = Path(args.recipe).expanduser().resolve()
    output = Path(args.output).expanduser().resolve()
    if not recipe.is_file():
        raise BuildError(f"build recipe is not a regular file: {recipe}")
    if not args.artifact:
        raise BuildError("at least one --artifact is required")

    user = remote_user(args.host)
    build_id = f"{user}_{int(time.time())}_{os.getpid()}_{args.name}"
    remote_dir = f"$HOME/Slurmy-builds/{build_id}"
    print(f"Slurmy build: {build_id}", flush=True)
    print(f"Remote directory: {args.host}:{remote_dir}", flush=True)

    with tempfile.TemporaryDirectory(prefix="slurmy-build-") as temporary:
        staging = Path(temporary)
        shutil.copy2(recipe, staging / "recipe.sh")
        has_context = args.context is not None
        if has_context:
            make_context_archive(Path(args.context).expanduser().resolve(), staging / "context.tar.gz")
        job_script = staging / "job.sh"
        job_script.write_text(build_job_script(args, has_context=has_context), encoding="utf-8")
        job_script.chmod(0o755)

        run(["ssh", "-T", "--", args.host, "bash", "-s", "--", build_id], input_text=REMOTE_PREPARE)
        run(["scp", "-q", "--", *(str(path) for path in staging.iterdir()), f"{args.host}:Slurmy-builds/{build_id}/incoming/"])
        submitted = run(
            ["ssh", "-T", "--", args.host, "bash", "-s", "--", build_id],
            input_text=REMOTE_SUBMIT,
            capture=True,
        )

    job_id = submitted.stdout.strip().split(";", 1)[0]
    if not job_id.isdigit():
        raise BuildError(f"sbatch returned an invalid job ID: {submitted.stdout.strip()!r}")
    print(f"Slurm job: {job_id}", flush=True)

    previous = ""
    while True:
        state_result = run(
            ["ssh", "-T", "--", args.host, "bash", "-s", "--", job_id],
            input_text=REMOTE_STATE,
            capture=True,
        )
        state = normalize_state(state_result.stdout)
        if state and state != previous:
            print(f"State: {state}", flush=True)
            previous = state
        if state in FINAL_STATES:
            break
        time.sleep(args.poll_interval)

    if state != "COMPLETED":
        log = run(
            ["ssh", "-T", "--", args.host, "bash", "-s", "--", build_id],
            input_text=REMOTE_LOG,
            capture=True,
        ).stdout.rstrip()
        if log:
            print("\n--- remote build log ---", file=sys.stderr)
            print(log, file=sys.stderr)
        raise BuildError(f"Slurm build job {job_id} ended in state {state or 'UNKNOWN'}")

    output.mkdir(parents=True, exist_ok=True)
    run(["rsync", "-a", "--", f"{args.host}:Slurmy-builds/{build_id}/output/", f"{output}/"])
    for artifact in args.artifact:
        if not (output / artifact).exists():
            raise BuildError(f"downloaded output is missing required artifact: {artifact}")
    print(f"Downloaded artifacts to {output}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="slurmy-build.py",
        description="Run a build recipe as a Slurm job and download its artifacts.",
    )
    parser.add_argument("--version", action="version", version=f"Slurmy build {VERSION}")
    parser.add_argument("--host", default=DEFAULT_HOST, help="SSH host alias (default: $SLURMY_HOST, or datalab)")
    parser.add_argument("--name", required=True, help="short build name used in job and directory names")
    parser.add_argument("--recipe", required=True, metavar="FILE", help="Bash build recipe to run on the compute node")
    parser.add_argument("--context", metavar="DIRECTORY", help="optional local directory unpacked into the build work directory")
    parser.add_argument("--output", required=True, metavar="DIRECTORY", help="local directory that receives the built artifacts")
    parser.add_argument("--artifact", action="append", type=checked_artifact, metavar="RELATIVE_PATH", help="required path below the output directory; repeat as needed")
    parser.add_argument("--cpus-per-task", type=int, default=4)
    parser.add_argument("--memory", type=slurm_memory, default="4096M", help="Slurm memory request (default: 4GiB)")
    parser.add_argument("--time", type=checked_time, default="00:30:00", help="Slurm time request (default: 00:30:00)")
    parser.add_argument("--sbatch-option", action="append", type=checked_sbatch_option, default=[], metavar="--OPTION=VALUE")
    parser.add_argument("--poll-interval", type=float, default=2.0, metavar="SECONDS")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if not NAME_RE.fullmatch(args.name):
        raise SystemExit("--name may contain only letters, digits, ., _, and -")
    if args.cpus_per_task <= 0:
        raise SystemExit("--cpus-per-task must be greater than zero")
    if args.poll_interval < 0.2:
        raise SystemExit("--poll-interval must be at least 0.2 seconds")
    try:
        execute_build(args)
    except (BuildError, OSError, tarfile.TarError) as exc:
        print(f"Slurmy build: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
